---
title: "Teori"
author: "Anders Nybakk"
code-fold: true
execute:
  warning: false  # Skjuler varselmeldinger
editor_options: 
  chunk_output_type: console
bibliography: resources/bib-final.bib
---


## Utholdenhetsprestasjon

Fra maten vi spiser henter kroppen ut karbohydrater og fett, og gjennom en rekke prosesser rundt og i mitokondriene, som Krebs syklus og oksidativ fosforylering, omdannes energien til adenosintrifosfat (ATP). ATP brukes som energibærer til alle cellene i kroppen – inkludert muskelceller (McArdle et al., 2023). Vår evne til å utnytte denne energien vil i stor grad påvirke utholdenhetsprestasjon (Tønnessen & Rønnestad, 2018). Produksjonen av ATP i mitokondriene er avhengig av oksygen (O2), og derfor vil følgende mekanismer være hovedfaktorer som påvirker en utøvers utholdenhetsprestasjon. Maksimalt oksygenopptak (VO2maks), utnyttingsgrad som er utøverens evne til å utnytte så mye som mulig av VO2maks og arbeidsøkonomi som er hvor effektivt utøveren klarer å bruke energien som produseres (Bassett & Howley, 2000). Varigheten på aktiviteten vil avgjøre hvilke av disse tre faktorene som påvirker prestasjonen mest (Tønnessen & Rønnestad, 2018).

### VO<sub>2max</sub>
VO2maks er den største mengden oksygen kroppen kan ta opp, transportere og bruke per minutt under maksimalt arbeid, og er den vanligste måten å angi den aerobe kapasiteten til en utøver (Bassett & Howley, 2000). Det er store individuelle forskjeller i VO2maks ut fra trenings- og idrettsbakgrunn og kjønn. Mannlige eliteutøvere i utholdenhetsidretter vil ofte ha VO2maks på 78-85 mL·kg-1·min-1, kvinnelige eliteutøvere i utholdenhetsidretter ligger ofte på 68-70 mL·kg-1·min-1, men unntak har blitt observert med både høyere og lavere målinger (Tønnessen & Rønnestad, 2018).

Det er flere fysiologiske faktorer som påvirker eller begrenser VO2maks, og vi kan dele disse begrensende faktorene inn i sentrale og perifere faktorer. De sentrale faktorene er minuttvolum, slagvolum og blodvolum(Montero et al., 2015). Det som kanskje er den viktigste begrensende faktoren, er maksimalt minuttvolum (Qmaks). Maksimalt minuttvolum består av hjertets maksimale slagfrekvens (Hfmaks) ganget med hjertets slagvolum (Montero et al., 2015). Hfmaks kan vi ikke påvirke, men hjertets slagvolum vil øke med trening, og dermed også minuttvolumet (Farrell et al., 2012; McArdle et al., 2023). Ved utholdenhetstrening skjer det flere forskjellige endringer som påvirker hjertets slagvolum. Hjertemuskelen selv blir større og sterkere som gir bedre pumpefunksjon, og hjertets evne til å fylles med blod blir også bedre. Dette skyldes blant annet økt blodvolum som igjen fører til økt venøs retur (Skattebo et al., 2020). Minuttvolum bestemmer oksygentransport til arbeidende muskler, og økt minuttvolum vil også gi økt oksygentransport (Mandić et al., 2023). Blodvolum som jeg nevnte over er en annen sentral begrensende faktor for VO2maks (Montero et al., 2015). Blodvolum er den totale mengden blod vi har i kroppen, altså plasma og blodceller. Hemoglobin eller røde blodceller er et protein som binder til seg oksygen og frakter det rundt til cellene i kroppen (McArdle et al., 2023). Både plasmavolum og hemoglobinmasse er trenbare faktorer som øker ved utholdenhetstrening. Økningen i plasmavolum og hemoglobinmakse fører derfor til økt oksygentransport og kan forklare en bedydelig del av forbedringer i VO2maks etter trening (Montero et al., 2015). 

De perifere faktorene som begrenser VO2maks, handler om distribusjon av oksygen til muskelcellene. Disse faktorene er blodtilførsel, kapillærtetthet, involvering av type 1 muskelfibre og mitokondriell tetthet og funksjon (Montero et al., 2015). Blodtilførsel handler om at blodstrømmen fordeles til arbeidende muskler under aktiviteten, slik at disse musklene får tilført mer oksygenrikt blod hvor oksygenet kan tas opp i muskelcellene (Mandić et al., 2023). For at dette opptaket – eller ekstraksjonen av oksygen skal være mest mulig effektiv er det behov for høy kapillærtetthet, altså et høyt antall kapillærer rundt muskelfibrene. Oksygenoverføringen skjer passivt ved hjelp av diffusjon, og høy kapillærtetthet gir kortere diffusjonsavstand og bedre oksygentilførsel. Studier viser at kapillærtettheten øker ved utholdenhetstrening (Montero et al., 2015). Involvering av type 1 muskelfibre handler mengden av aktiv muskelmasse i aktiviteten. Ved å aktivere en større andel av muskelfibre vil kroppens oksygenopptak øke ettersom det samlede energibehovet i muskelvevet også øker (Montero et al., 2015; Skattebo et al., 2020). Den siste perifere faktoren er mitokondriell tetthet og funksjon. Mitokondriene er organellene i cellene hvor mesteparten av energiproduksjonen foregår. Antall mitokondrier i muskelcellene er derfor en faktor som påvirker hvor mye energi musklene kan produsere og da også hvor mye oksygen som kan tas opp (Montero et al., 2015). I tillegg er det mitokondrienes funksjonelle kapasitet avgjørende for oksygenopptaket. Funksjonen til mitokondriene påvirkes blant annet av oksidative enzymer og strukturelle tilpasninger. Utholdenhetstrening påvirker både mitokondriell tetthet og funksjon positivt (Mandić et al., 2023; Skattebo et al., 2020).

VO2maks, er altså kroppens maksimale evne til å ta opp, transportere og gjøre seg nytte av, og begrenses av faktorene som nevnes over. Desto høyere VO2maks en utøver har desto større kapasitet har vedkommende til å produsere energi aerobisk, og VO2maks kan derfor beskrives som en øvre grense for aerob energiproduksjon (Bassett & Howley, 2000). Prestasjon i utholdenhetsidretter er sterkt knyttet til VO2maks, men er ikke ene og alene bestemmende for utholdenhetsprestasjon. I tillegg til VO2maks er utnyttingsgrad og arbeidøkonomi avgjørende for utholdenhetsprestasjon (Bassett & Howley, 2000).


### Utnyttingsgrad
VO2maks er altså den største mengden oksygen en utøver kan ta opp og gjøre nytte av i kroppen, men det vil ikke være mulig å nyttiggjøre seg av VO2maks i alle konkurranser (Tønnessen & Rønnestad, 2018). Normalt sett vil man bare kunne holde en intensitet som fremkaller VO2maks i 5-8 min (Joyner & Coyle, 2008). For utholdenhetsutøver med lengre konkurransetid vil det altså ikke være mulig å benytte seg av hele VO2maks , men det vil da være nyttig å kunne benytte seg av så stor del av VO2maks som mulig  (Tønnessen & Rønnestad, 2018). Utnyttingsgrad kan forklares som den prosentandelen av VO2maks som kan opprettholdes over tid i utholdenhetsarbeid (Bassett & Howley, 2000; Joyner & Coyle, 2008).

Vi har to hovedprosesser for energifrigjøring i cellene. Aerob energifrigjøring (med oksygen) og anaerob energifrigjøring (uten oksygen). I utholdenhetsidretter er det aerob energifrigjøring som er dominerende, men ettersom intensiteten på arbeidet stiger vil også anaerob energifrigjøring bli mer gjeldende. Ved anaerob energifrigjøring produseres melkesyre som umiddelbart spaltes til laktat og frie H+-ioner. Laktat fungerer som en energibærer, men H+-ionene vil hemme ; 1: musklenes tverrbroer, 2: Ca2+ binding til troponin, 3: Na+-K+ pumper, 4: SR-pumper og 5: glykolysen (Farrell et al., 2012). Det er altså akkumuleringen av H+-ioner , ikke laktat som fører til redusert pH i musklene – eller acidose som hemmer musklenes evne til kontraksjon og bidrar til muskulær trøtthet (Grgic et al., 2021; Shannon et al., 2024). Når vi er i aktivitet vil laktatkonsentrasjonen stabilisere seg ved en gitt intensitet, men hvis intensiteten er høy nok vil akkumuleringen av laktat og H+-ioner øke selv om intensiteten er den samme – gitt at den er høy nok. Den høyeste arbeidsintensiteten vi kan holde der laktatkonsentrasjonen stabiliserer seg er det vi kaller «laktatterskel» (Tønnessen & Rønnestad, 2018). Utnyttingsgraden til en utøver er strekt knyttet til en laktatterskel og estimeres ofte som hvor stor prosentandel av VO2maks som utnyttes på denne intensiteten (Bassett & Howley, 2000; Tønnessen & Rønnestad, 2018). For godt trente utholdenhetsutøvere vil utnyttingsgraden ligge rundt 70-90 % av VO2maks (Joyner & Coyle, 2008).

Som VO2maks er også utnyttingsgraden til en utøver trenbar og kan forbedres. Mens VO2maks hovedsakelig begrenses av sentrale kardiovaskulære faktorer, er utnyttingsgraden mer knyttet til perifere faktorer (Bassett & Howley, 2000). Kapillærtetthet, aerobe enzymer og mitokondriell tetthet og funksjon er alle begrensende faktorer for utnyttingsgraden og er som tidligere nevnt trenbare (Montero et al., 2015; Skattebo et al., 2020; Tønnessen & Rønnestad, 2018).  


### Arbeidsøkonomi

Arbeidsøkonomi er den siste hovedfaktoren som påvirker utholdenhetsprestasjon og defineres som oksygenforbruket ved en gitt arbeidsintensitet eller hastighet. En utøver med god arbeidsøkonomi vil ha lavere oksygenforbruk ved en gitt intensitet enn en utøver med dårlig arbeidøkonomi (Bassett & Howley, 2000; Joyner & Coyle, 2008). Det har blitt observert store individuelle variasjoner i arbeidsøkonomien ved en gitt hastighet. Joyner og Coyle skriver at arbeidsøkonomien på sykkel kan variere med 20-30 % (2008), mens Tønnessen og Rønnestad raporterer en forskjell på 15 % (2018). Så store forskjeller på arbeidsøkonomi vil ha en sterk påvirkning på utholdenhetsprestasjon og kan være svært avgjørende – spesielt for individer med relativt lik VO2maks (Bassett & Howley, 2000; Tønnessen & Rønnestad, 2018).

Flere studier viser at arbeidsøkonomi kan forbedres med langvarig trening, men det kan være vanskelig å peke på nøyaktig hvilke fysiologiske faktorer som påvirkes. Trolig er det en kombinasjon av mekaniske og fysiologiske forandringer som er forklaringen. Teknikk og utstyr vi for eksempel være noe av forklaringen, men muskelfibertypesammensetning har også vist seg å være relevant (Joyner & Coyle, 2008; Tønnessen & Rønnestad, 2018). Flere studier peker på at det er fordelaktig for utøvere å ha en stor andel type I-fiber med tanke på arbeidsøkonomi. Tønnesen og Rønnestad påpeker også at styrketrening kan forbedre arbeidsøkonomien og mener at omdanningen muskelfibertype fra type IIX til type IIA kan være forklaringen på dette (Tønnessen & Rønnestad, 2018). Joyner og Coyle påpeker også en effekt av muskel-sene-elastisitet, men knytter dette mer opp til løping enn til sykling ettersom det er en mer komplisert bevegelse hvor denne elastisiteten lettere kan nyttiggjøres (2008).

VO2maks, utnyttingsgrad og arbeidsøkonomi er altså tre hovedfaktorer som sammen i stor grad påvirker utholdenhetsprestasjon (Bassett & Howley, 2000). Alle disse tre faktorene kan påvirkes av trening som vi har sett over, men det finnes også behandlinger som potensielt kan gi en mer akutt positiv effekt på disse faktorene – og dermed også på utholdenhetsprestasjon.


## Apné
Det har lenge vært kjent at å gjennomføre apné (frivillig pustestopp) med ansiktet i kaldt vann utløser noe som blir kalt en dykkerefleks. Denne dykkerefleksen består av en aktiv kontraksjon av milten (Baković et al., 2003, 2005). I milten er det lagret hemoglobin, og denne kontraksjonen fører til at hemoglobinet frigjøres ut i blodbanen, slik at hemoglobinkonsentrasjonen (Hb-konsentrasjon) i blodet øker, som igjen øker blodets evne til oksygentransport (Bouten et al., 2025; Lindblom et al., 2024).  Størst miltrespons får man ved statisk maksimal apné i kaldt vann, noe som gir en sterkere kontraksjon, og dermed en større frigjøring av hemoglobin (Bouten et al., 2025; Holmström et al., 2021; Lindblom et al., 2024). Repeterte serier med apne fører ikke til en siginifikant forskjell på sammentrekning eller Hb-frigjøring i forhold til en èn repetisjon (Bouten et al., 2025). Utøverne i en studie raporterte også bedre opplevd klarhet til testen ved bare en repetisjon (Bouten et al., 2020).

Flere studier viser at miltkontraksjon som følge av apné kan føre til en økning på 3,3-4,5 % i Hb-konsentrasjon (Holmström et al., 2021; Lindblom et al., 2024). En slik økning i Hb-konsentrasjon kan gi en betydelig økning i VO2maks, noe som i teorien kan bedre utholdenhetsprestasjonen til utøveren (Bouten et al., 2025). Effekten av apné ser ut til å være rask og kortvarig. Milten kontraherer umiddelbart og innen få minutt vil det være mulig å observere en økning i Hb-konsentrasjon. Det er noe variasjon i studiene hvor lenge denne økningen varer, men Bouten et al antar at den kan vare så mye som 10-20 minutter (Bouten et al., 2025). I tillegg til økt Hb-konsentrasjon har det også blitt observert lavere hvilepuls etter apné – noe som igjen kan tyde på at det er mer oksygen tilgjengelig (Baković et al., 2003, 2005).

Til tross for at flere studier har målt disse fysiologiske endringene ved apné er det til nå lite som støtter en effekt på utholdenhetsprestasjon. I en studie fra 2021 ble det observert en positiv effekt på en sykkeltest til utmattelse på 150 % av peak power. Studien så en forbedret prestasjon på opp til 11 % (Bourdas, 2021). På lengre utholdenhetstester er det foreløpig lite å vise til, men med økningen av Hb-masse er det et potensiale ved denne behandlingen[


## Bikarbonat
Som tidligere nevnt produserer musklene melkesyre ved arbeid med høy intensitet. Melkesyren spaltes umiddelbart til laktat og H+-ion, som gjør at pH-verdien i cellene synker som igjen fører til acidose som hemmer musklenes evne til å kontrahere og vi får følelsen av at muskulaturen stivner (Farrell et al., 2012; Grgic et al., 2021; Shannon et al., 2024). Kroppen forsøker å hindre acidose ved å produsere bikarbonat (HCO3-) som fungerer som en buffer. Bikarbonatet binder seg til de frie H+-ionene I cellene og normaliserer dermed pH-verdien (McArdle et al., 2023). 

På grunn av denne buffereffekten har inntak av natriumbikarbonat (NaHCO3-) før trening og konkurranse vært relativt vanlig i lang tid. Da natriumbikarbonat kommer i kontakt med magevæsken spaltes det til Na og HCO3- som bidrar til økt bufferkapasitet (Grgic et al., 2021). Overskuddet av HCO3- fører til økt transport av H+-ioner og laktat og en høyere pH-verdi i cellene og blodet. Dette gjør at man kan ha et høyere nivå av laktat og likevel unndå acidose og påfølgende hemminger i muskelkontraksjon (Egger et al., 2014; Gough et al., 2018). Et mål med inntak av bikarbonat er å oppnå alkalose før trening eller konkurranse. Dette vil si at pH-verdien i blodet er over 7 – altså litt basisk før start (Gough et al., 2018). I tillegg til høyere start pH viser også flere studier at fallet i pH er mindre ved bruk av bikarbonat enn ved placebo (Egger et al., 2014; Shannon et al., 2024). Disse faktorene kan til sammen gi utøverne en økt toleranse for arbeid over laktatterskel (Egger et al., 2014). På kortere distanser er det godt dokumentert effekt av å bruke bikarbonat, men det er tynnere evidens på lengre distanser. Likevel er det studier som har funnet en effekt på lengre distanser som 40 km også (Shannon et al., 2024, 2026).

Et kjent problem med bruken av bikarbonat som tilskudd er at mange får mageproblemer. Det basiske stoffet bikarbonat vil reagere med saltsyren (HCl) i magesekken og danne karbonsyre (H2CO3) som igjen vil spaltes til karbondioksid (CO2) og vann (H2O) (Grgic et al., 2021).

	NaHCO3  HCO3- + Na+
	
	HCL + HCO3-  H2CO3 + Cl-
	
	H2CO3  CO2 + H2O
	
Denne frigjøringen av CO2 som resulterer i at mange opplever mageproblemer, raping og oppblåsthet (Grgic et al., 2021). Flere studier har funnet at disse magesymptomene kan reduseres ved bruk av bikarbonat i form av mikrokapsler kombinert med en hydrogel (Gough & Sparks, 2024; Grgic et al., 2021; Shannon et al., 2024).



## Målsetting, problemstilling og hypotese

Målsetting: Målet for denne studien er å undersøke om apné og bikarbonat kan brukes som akutt prestasjonsfremmende metoder på sykkelprestasjon med relativ lang varighet.

Problemstilling: Kan apné brukes som et hjelpemiddel for å øke hemoglobinnivået i blodet og dermed bidra til bedre utholdenhetsprestasjon, og vil effekten eventuelt være like stor som effekten av bikarbonattilskudd?

Hypotese 1: Både apné og bikarbonat fører til signifikant bedre resultat på en 20 minutters test for maksimal sykkelprestasjon

Hypotese 2: Bikarbonat fører til signifikant bedre resultat på en 20 minutters test for maksimal sykkelprestasjon, men apné har ingen signifikant påvirkning.
